package org.gik.cloud.storage.common;

public enum MessageType {
    REFRESH_UI, AUTH, AUTH_CODE_FAIL, GET_DIR, SEND_FILE_FROM_SERVER, SEND_FILE_TO_SERVER, MOVE_FILE_FROM_SERVER, MOVE_FILE_TO_SERVER,DELETE, NONE;

}
