package org.gik.cloud.storage.common;

public enum MessageType {
    DELETE_FILE_ON_CLIENT, REFRESH_UI, AUTH, AUTH_CODE_FAIL, GET_DIR,CLEAR_SERVER_LIST,
    COPY_FILE_FROM_SERVER, COPY_FILE_TO_SERVER, MOVE_FILE_FROM_SERVER, MOVE_FILE_TO_SERVER,DELETE, NONE;

}
